/**
 * Custom Cloudflare Worker entrypoint.
 *
 * OpenNext generates `.open-next/worker.js` as the real Next.js request
 * handler. We wrap it with DataFast's `withAICrawlerTracking` (the sanctioned
 * Cloudflare Workers pattern from https://datafa.st/docs/bot-traffic-tracking)
 * so server-side bot-traffic tracking runs on every request.
 *
 * We can't use Next.js `proxy`/middleware for this: Next 16 proxy is
 * Node-runtime only and OpenNext's Cloudflare adapter rejects Node middleware
 * ("Node.js middleware is not currently supported"). And `functions/_middleware.ts`
 * only runs on Cloudflare Pages — this app deploys as a Worker via OpenNext.
 *
 * This file is bundled by Wrangler, not by `next build`, so it is excluded
 * from the Next.js TypeScript project (see tsconfig.json). Types are kept
 * self-contained to avoid pulling in @cloudflare/workers-types.
 */
import { withAICrawlerTracking } from "@datafast/ai-crawl";
// @ts-expect-error - generated by `opennextjs-cloudflare build`
import openNextWorker from "./.open-next/worker.js";

// Re-export any Durable Object classes OpenNext bundles (cache/queue), so
// Wrangler bindings that reference them keep resolving.
// @ts-expect-error - generated by `opennextjs-cloudflare build`
export * from "./.open-next/worker.js";

// `withAICrawlerTracking` runs the OpenNext handler, then reports the crawler
// request + response status to DataFast in the background via ctx.waitUntil.
// It never blocks or buffers the response body.
const fetch = withAICrawlerTracking(
  (request: Request, env: unknown, ctx: unknown): Promise<Response> =>
    openNextWorker.fetch(request, env, ctx),
  {
    websiteId: "dfid_g2ojbeIQME0i1UQ8TRicK",
  },
);

const handler = { fetch };
export default handler;
